### ISSUE TITLE
os 10.10.3 trouble

### ISSUE THREAD

**Issue by nekrut** [ialbert/pyblue#5]
after installing with pip:

`$ pyblue 
Traceback (most recent call last):
  File "/usr/local/bin/pyblue", line 2, in <module>
    from pyblue import pyblue
  File "/Library/Python/2.7/site-packages/pyblue/pyblue.py", line 8, in <module>
    from django.template import Context, Template, get_templatetags_modules
ImportError: cannot import name get_templatetags_modules
antons-macbook-air:galaxy anton$ pyblue
Traceback (most recent call last):
  File "/usr/local/bin/pyblue", line 2, in <module>
    from pyblue import pyblue
  File "/Library/Python/2.7/site-packages/pyblue/pyblue.py", line 8, in <module>
    from django.template import Context, Template, get_templatetags_modules
ImportError: cannot import name get_templatetags_modules`

**Comment by ialbert** [comment]
the new django breaks it (i have it set as django>=1.7 but 1.8 is out)

do a 

    pip install 'django==1.7'

**Comment by nekrut** [comment]
that fixes it. tx
